"""
=============================================================================
PART 2: Data Manipulation and Visualization
=============================================================================
Programming for Data Science - Final Project
Universidad Politécnica de Madrid

Description:
    Loads the CSV files generated by the scraper (Part 1), performs
    data manipulation/wrangling/transformation using techniques covered
    in the course, and answers 3 analysis questions with visualizations.

    Questions:
      Q1: Which genre has the highest average rating, and how do
          rating distributions compare across genres?
      Q2: Is there a "golden era" of cinema? How are top-rated films
          distributed across decades?
      Q3: Which directors dominate top-rated lists? Are they genre
          specialists or versatile across genres?

    Course techniques used:
      - pd.concat           (04_data_wrangling: Concatenating Data Sets)
      - fillna, dropna      (05_data_transformation: Handling Missing Data)
      - astype, to_numeric  (03_data_manipulation: Data Types)
      - map                 (05_data_transformation: Function or Mapping)
      - duplicated          (05_data_transformation: Removing Duplicates)
      - pd.cut              (05_data_transformation: Discretization/Binning)
      - groupby + agg       (04_data_wrangling: Group-by Object)
      - pd.crosstab         (04_data_wrangling: Cross-tabulation)
      - value_counts         (06_use_case: Data Arrangement)
      - sort_values          (03_data_manipulation: Sorting and Ranking)

Dependencies:
    pip install pandas matplotlib numpy

Usage:
    python analysis.py
=============================================================================
"""

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')  # Non-GUI backend (compatible with PyDroid3)
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import os
import glob


# =============================================================================
# CONFIGURATION
# =============================================================================

DATA_DIR = "data"
OUTPUT_DIR = "plots"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Plot style
plt.rcParams['figure.figsize'] = (14, 7)
plt.rcParams['font.size'] = 11
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['axes.labelsize'] = 12

# Genre colors (consistent across all plots)
GENRE_COLORS = {
    'Drama':    '#3266ad',
    'Comedy':   '#639922',
    'Thriller': '#BA7517',
    'Sci-Fi':   '#534AB7',
    'Horror':   '#A32D2D',
}


# =============================================================================
# STEP 1: DATA LOADING — pd.concat (04_data_wrangling)
# =============================================================================

def load_data(data_dir):
    """
    Load all CSV files from Part 1 and combine into a single DataFrame.

    Uses pd.concat to concatenate multiple DataFrames, as covered in
    04_data_wrangling (Concatenating Data Sets).

    Parameters:
        data_dir (str): Path to directory with CSV files.

    Returns:
        pd.DataFrame: Combined DataFrame with all genres.
    """
    print("=" * 70)
    print("STEP 1: DATA LOADING (pd.concat)")
    print("=" * 70)

    csv_files = sorted(glob.glob(os.path.join(data_dir, "filmaffinity_*.csv")))

    if not csv_files:
        raise FileNotFoundError(f"No CSV files found in {data_dir}")

    # Read each CSV into a list of DataFrames
    dataframes = []
    for filepath in csv_files:
        df = pd.read_csv(filepath, encoding='utf-8-sig')
        genre = os.path.basename(filepath).replace(
            "filmaffinity_", "").replace(".csv", "")
        print(f"  Loaded: {os.path.basename(filepath)} "
              f"-> {len(df)} rows, genre='{genre}'")
        dataframes.append(df)

    # Concatenate all DataFrames (pd.concat from 04_data_wrangling)
    df = pd.concat(dataframes, ignore_index=True)

    print(f"\n  Combined: {df.shape[0]} rows x {df.shape[1]} columns")
    print(f"  Columns: {list(df.columns)}")

    return df


# =============================================================================
# STEP 2: DATA WRANGLING & CLEANING
#   - isnull, fillna, dropna  (05_data_transformation: Missing Data)
#   - astype, to_numeric       (03_data_manipulation)
#   - map                      (05_data_transformation: Mapping)
#   - duplicated               (05_data_transformation: Removing Duplicates)
# =============================================================================

def clean_data(df):
    """
    Clean and wrangle the raw DataFrame.

    Techniques used (all from course slides):
      - isnull().sum()   -> detect missing values
      - fillna()         -> fill missing text fields
      - dropna()         -> drop rows without essential fields
      - astype()         -> convert data types
      - map()            -> standardize genre labels
      - duplicated()     -> detect movies appearing in multiple genres

    Parameters:
        df (pd.DataFrame): Raw combined DataFrame.

    Returns:
        pd.DataFrame: Cleaned DataFrame.
    """
    print("\n" + "=" * 70)
    print("STEP 2: DATA WRANGLING & CLEANING")
    print("=" * 70)

    # --- 2.1: Check for missing values (isnull from 05_data_transformation) ---
    print("\n  2.1 Missing values:")
    missing = df.isnull().sum()
    print(missing[missing > 0].to_string()
          if missing.sum() > 0 else "    None found")

    # --- 2.2: Handle missing values (fillna from 05_data_transformation) ---
    # Fill missing text fields with 'Unknown'
    for col in ['director', 'cast', 'country']:
        n_missing = df[col].isnull().sum()
        if n_missing > 0:
            df[col] = df[col].fillna('Unknown')
            print(f"  -> Filled {n_missing} missing '{col}' with 'Unknown'")

    # Drop rows without year (essential for decade analysis)
    rows_before = len(df)
    df = df.dropna(subset=['year'])
    dropped = rows_before - len(df)
    if dropped > 0:
        print(f"  -> Dropped {dropped} rows with missing year")

    # --- 2.3: Type conversion (astype from 03_data_manipulation) ---
    df['year'] = df['year'].astype(int)
    df['rating'] = pd.to_numeric(df['rating'], errors='coerce')
    df['votes'] = pd.to_numeric(df['votes'], errors='coerce').fillna(0).astype(int)
    print("  2.3 Type conversions: year->int, rating->float, votes->int")

    # --- 2.4: Standardize genre labels (map from 05_data_transformation) ---
    genre_labels = {
        'drama': 'Drama',
        'comedy': 'Comedy',
        'thriller': 'Thriller',
        'sci_fi': 'Sci-Fi',
        'horror': 'Horror',
    }
    df['genre'] = df['genre'].map(genre_labels)
    print(f"  2.4 Genre labels standardized: {list(df['genre'].unique())}")

    # --- 2.5: Detect duplicates (duplicated from 05_data_transformation) ---
    dupes = df[df.duplicated(subset=['title', 'year'], keep=False)]
    n_dupes = dupes['title'].nunique()
    print(f"\n  2.5 Duplicate detection: {n_dupes} movies appear in 2+ genres")
    if n_dupes > 0:
        for title in dupes['title'].unique()[:5]:
            genres = dupes[dupes['title'] == title]['genre'].tolist()
            print(f"      '{title}' -> {genres}")
        if n_dupes > 5:
            print(f"      ... and {n_dupes - 5} more")

    # --- Summary ---
    print(f"\n  Final: {df.shape[0]} rows x {df.shape[1]} columns")
    print(f"  Year range: {df['year'].min()} – {df['year'].max()}")
    print(f"  Rating range: {df['rating'].min():.1f} – {df['rating'].max():.1f}")

    return df


# =============================================================================
# STEP 3: DATA TRANSFORMATION
#   - Derived column: decade     (arithmetic on year)
#   - pd.cut                     (05_data_transformation: Discretization)
#   - groupby + agg              (04_data_wrangling: Group-by Object)
#   - pd.crosstab                (04_data_wrangling)
#   - value_counts               (06_use_case: Data Arrangement)
# =============================================================================

def transform_data(df):
    """
    Create derived columns and aggregated views for analysis.

    Techniques used:
      - Derived column: decade = (year // 10) * 10
      - pd.cut: bin ratings into categories
      - groupby + agg: compute stats per genre and decade
      - pd.crosstab: director × genre matrix
      - value_counts: director frequency

    Parameters:
        df (pd.DataFrame): Cleaned DataFrame.

    Returns:
        tuple: (df, genre_stats, decade_stats, director_genre_ct)
    """
    print("\n" + "=" * 70)
    print("STEP 3: DATA TRANSFORMATION")
    print("=" * 70)

    # --- 3.1: Create decade column (derived from year) ---
    df['decade'] = (df['year'] // 10) * 10
    df['decade_label'] = df['decade'].astype(str) + 's'
    print(f"  3.1 Created 'decade' column: "
          f"{sorted(df['decade'].unique())}")

    # --- 3.2: Discretization with pd.cut (05_data_transformation) ---
    # Bin ratings into categories using pd.cut
    bins = [0, 7.5, 8.0, 8.5, 10]
    labels = ['Good (≤7.5)', 'Very Good (7.6–8.0)',
              'Excellent (8.1–8.5)', 'Outstanding (>8.5)']
    df['rating_category'] = pd.cut(df['rating'], bins=bins, labels=labels)
    print(f"  3.2 Rating categories (pd.cut):")
    # value_counts (06_use_case)
    cat_counts = df['rating_category'].value_counts()
    for cat, count in cat_counts.items():
        print(f"      {cat}: {count} movies")

    # --- 3.3: Genre statistics (groupby + agg from 04_data_wrangling) ---
    genre_stats = df.groupby('genre').agg(
        mean_rating=('rating', 'mean'),
        median_rating=('rating', 'median'),
        std_rating=('rating', 'std'),
        min_rating=('rating', 'min'),
        max_rating=('rating', 'max'),
        total_votes=('votes', 'sum'),
        avg_votes=('votes', 'mean'),
        movie_count=('title', 'count'),
    ).round(2)
    # sort_values (03_data_manipulation)
    genre_stats = genre_stats.sort_values('mean_rating', ascending=False)
    print(f"\n  3.3 Genre statistics (groupby + agg):")
    print(genre_stats.to_string())

    # --- 3.4: Decade statistics (groupby + agg) ---
    decade_stats = df.groupby(['decade', 'decade_label']).agg(
        mean_rating=('rating', 'mean'),
        movie_count=('title', 'count'),
        avg_votes=('votes', 'mean'),
    ).round(2).reset_index()
    decade_stats = decade_stats.sort_values('decade')
    print(f"\n  3.4 Decade statistics:")
    print(decade_stats.to_string(index=False))

    # --- 3.5: Director × Genre cross-tabulation (pd.crosstab) ---
    # pd.crosstab from 04_data_wrangling
    director_genre_ct = pd.crosstab(df['director'], df['genre'])

    # Filter to directors with 2+ total appearances
    director_totals = director_genre_ct.sum(axis=1)
    director_genre_ct = director_genre_ct[director_totals >= 2]
    director_genre_ct = director_genre_ct.loc[
        director_genre_ct.sum(axis=1).sort_values(ascending=False).index
    ]
    print(f"\n  3.5 Director × Genre crosstab "
          f"({len(director_genre_ct)} directors with 2+ appearances):")
    print(director_genre_ct.head(10).to_string())

    return df, genre_stats, decade_stats, director_genre_ct


# =============================================================================
# STEP 4: VISUALIZATION — Q1: Genre Rating Comparison
# =============================================================================

def question_1(df, genre_stats, output_dir):
    """
    Q1: Which genre has the highest average rating, and how do
    rating distributions compare across genres?

    Plots:
      A) Box plot of rating distributions by genre
      B) Bar chart of mean ratings with std dev error bars
    """
    print("\n" + "=" * 70)
    print("Q1: Genre Rating Comparison")
    print("=" * 70)

    fig, axes = plt.subplots(1, 2, figsize=(16, 7))

    # Order genres by mean rating (descending)
    genres_order = genre_stats.index.tolist()

    # --- Plot A: Box plot ---
    genre_data = [df[df['genre'] == g]['rating'].values for g in genres_order]

    bp = axes[0].boxplot(
        genre_data, labels=genres_order, patch_artist=True,
        medianprops=dict(color='black', linewidth=2),
        whiskerprops=dict(linewidth=1.2),
        capprops=dict(linewidth=1.2),
    )
    for patch, genre in zip(bp['boxes'], genres_order):
        patch.set_facecolor(GENRE_COLORS[genre])
        patch.set_alpha(0.75)

    axes[0].set_title('Rating distributions by genre')
    axes[0].set_ylabel('Rating (0–10)')
    axes[0].set_xlabel('Genre')
    axes[0].grid(axis='y', alpha=0.3)

    # --- Plot B: Bar chart with error bars ---
    x = range(len(genres_order))
    means = [genre_stats.loc[g, 'mean_rating'] for g in genres_order]
    stds = [genre_stats.loc[g, 'std_rating'] for g in genres_order]
    bar_colors = [GENRE_COLORS[g] for g in genres_order]

    bars = axes[1].bar(
        x, means, yerr=stds, capsize=5,
        color=bar_colors, alpha=0.85,
        edgecolor='black', linewidth=0.5,
    )
    axes[1].set_xticks(x)
    axes[1].set_xticklabels(genres_order)
    axes[1].set_title('Average rating by genre (± std dev)')
    axes[1].set_ylabel('Average Rating')
    axes[1].set_xlabel('Genre')
    axes[1].set_ylim(7.0, 9.0)
    axes[1].grid(axis='y', alpha=0.3)

    # Add value labels on bars
    for bar, mean_val in zip(bars, means):
        axes[1].text(
            bar.get_x() + bar.get_width() / 2., bar.get_height() + 0.05,
            f'{mean_val:.2f}', ha='center', va='bottom', fontweight='bold',
        )

    plt.tight_layout()
    path = os.path.join(output_dir, "Q1_genre_ratings.png")
    plt.savefig(path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  Saved: {path}")

    # --- Answer ---
    best = genre_stats.iloc[0]
    worst = genre_stats.iloc[-1]
    print(f"\n  ANSWER:")
    print(f"  -> Highest avg rating: {genre_stats.index[0]} "
          f"({best['mean_rating']:.2f})")
    print(f"  -> Lowest avg rating: {genre_stats.index[-1]} "
          f"({worst['mean_rating']:.2f})")
    print(f"  -> Drama has a tight cluster (std={best['std_rating']:.2f}), "
          f"while Horror shows more spread (std={worst['std_rating']:.2f}).")
    print(f"  -> The gap between best and worst genre average is "
          f"{best['mean_rating'] - worst['mean_rating']:.2f} points.")


# =============================================================================
# STEP 4: VISUALIZATION — Q2: Golden Era of Cinema
# =============================================================================

def question_2(df, decade_stats, output_dir):
    """
    Q2: Is there a "golden era" of cinema? How are top-rated films
    distributed across decades, and does average rating vary by era?

    Plots:
      A) Dual-axis: movie count per decade (bars) + avg rating (line)
      B) Stacked bar: genre composition per decade (from pd.crosstab)
    """
    print("\n" + "=" * 70)
    print("Q2: Golden Era Analysis")
    print("=" * 70)

    fig, axes = plt.subplots(1, 2, figsize=(18, 7))

    ds = decade_stats.sort_values('decade')
    x_labels = ds['decade_label'].values
    x_pos = range(len(x_labels))

    # --- Plot A: Dual-axis (bars + line) ---
    color_bar = '#3266ad'
    color_line = '#A32D2D'

    bars = axes[0].bar(
        x_pos, ds['movie_count'], color=color_bar, alpha=0.7,
        label='Number of movies', edgecolor='black', linewidth=0.5,
    )
    axes[0].set_ylabel('Number of top-rated movies', color=color_bar)
    axes[0].tick_params(axis='y', labelcolor=color_bar)

    # Secondary axis for average rating
    ax2 = axes[0].twinx()
    ax2.plot(
        x_pos, ds['mean_rating'], color=color_line, marker='o',
        linewidth=2.5, markersize=7, label='Avg rating',
    )
    ax2.set_ylabel('Average rating', color=color_line)
    ax2.tick_params(axis='y', labelcolor=color_line)
    ax2.set_ylim(7.4, 8.5)

    axes[0].set_xticks(x_pos)
    axes[0].set_xticklabels(x_labels, rotation=45, ha='right')
    axes[0].set_xlabel('Decade')
    axes[0].set_title('Movie count and average rating by decade')

    # Combine legends from both axes
    lines1, labels1 = axes[0].get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    axes[0].legend(lines1 + lines2, labels1 + labels2, loc='upper left')

    # --- Plot B: Stacked bar — genre distribution per decade ---
    # pd.crosstab (04_data_wrangling)
    pivot = pd.crosstab(df['decade_label'], df['genre'])

    # Sort by decade order
    decade_order = sorted(
        df['decade_label'].unique(),
        key=lambda x: int(x.replace('s', '')),
    )
    pivot = pivot.reindex(decade_order)

    pivot.plot(
        kind='bar', stacked=True, ax=axes[1],
        color=[GENRE_COLORS.get(c, '#999') for c in pivot.columns],
        edgecolor='black', linewidth=0.3,
    )
    axes[1].set_title('Genre distribution of top-rated movies by decade')
    axes[1].set_xlabel('Decade')
    axes[1].set_ylabel('Number of movies')
    axes[1].legend(title='Genre', bbox_to_anchor=(1.02, 1), loc='upper left')
    axes[1].tick_params(axis='x', rotation=45)

    plt.tight_layout()
    path = os.path.join(output_dir, "Q2_golden_era.png")
    plt.savefig(path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  Saved: {path}")

    # --- Answer ---
    peak = ds.loc[ds['movie_count'].idxmax()]
    highest = ds.loc[ds['mean_rating'].idxmax()]
    print(f"\n  ANSWER:")
    print(f"  -> Most top-rated movies: {peak['decade_label']} "
          f"({int(peak['movie_count'])} films)")
    print(f"  -> Highest avg rating: {highest['decade_label']} "
          f"({highest['mean_rating']:.2f})")
    print(f"  -> Older decades (1920s–1940s) show higher average ratings,")
    print(f"     likely due to survivorship bias: only the best classics")
    print(f"     remain in collective memory and receive high ratings today.")
    print(f"  -> The 1990s have the most entries but a lower average,")
    print(f"     reflecting broader representation rather than higher quality.")


# =============================================================================
# STEP 4: VISUALIZATION — Q3: Director Dominance
# =============================================================================

def question_3(df, director_genre_ct, output_dir):
    """
    Q3: Which directors dominate across multiple genre rankings?
    Are they genre specialists or versatile across genres?

    Plots:
      A) Horizontal bar: top 15 directors by frequency, colored by
         number of genres (specialist vs versatile)
      B) Heatmap: director × genre appearance matrix
    """
    print("\n" + "=" * 70)
    print("Q3: Director Dominance")
    print("=" * 70)

    fig, axes = plt.subplots(1, 2, figsize=(18, 9))

    # --- Plot A: Horizontal bar chart ---
    # value_counts + sort_values (03_data_manipulation, 06_use_case)
    director_counts = df['director'].value_counts().head(15)
    top_directors = director_counts.index.tolist()

    # Count number of genres per director
    genres_per_director = df.groupby('director')['genre'].nunique()

    # Assign colors by versatility
    bar_colors = []
    for d in top_directors:
        n = genres_per_director.get(d, 1)
        if n >= 3:
            bar_colors.append('#534AB7')   # purple: 3+ genres
        elif n == 2:
            bar_colors.append('#1D9E75')   # teal: 2 genres
        else:
            bar_colors.append('#BA7517')   # amber: 1 genre

    y_pos = range(len(director_counts))
    axes[0].barh(
        y_pos, director_counts.values, color=bar_colors,
        edgecolor='black', linewidth=0.5,
    )
    axes[0].set_yticks(y_pos)
    axes[0].set_yticklabels(director_counts.index)
    axes[0].set_xlabel('Appearances in top-30 lists')
    axes[0].set_title('Top 15 directors by frequency in rankings')
    axes[0].invert_yaxis()

    # Add genre count + avg rating annotation
    for i, (count, director) in enumerate(
        zip(director_counts.values, top_directors)
    ):
        n_genres = genres_per_director.get(director, 1)
        avg_r = df[df['director'] == director]['rating'].mean()
        axes[0].text(
            count + 0.15, i,
            f'{n_genres} genres · avg {avg_r:.1f}',
            va='center', fontsize=9, color='#555',
        )

    # Legend for colors
    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor='#534AB7', label='3+ genres (versatile)'),
        Patch(facecolor='#1D9E75', label='2 genres'),
        Patch(facecolor='#BA7517', label='1 genre (specialist)'),
    ]
    axes[0].legend(handles=legend_elements, loc='lower right', fontsize=9)

    # --- Plot B: Heatmap (from pd.crosstab result) ---
    # Use the director_genre_ct from transform_data (pd.crosstab)
    heatmap_data = director_genre_ct.head(15)
    # Sort by total appearances
    heatmap_data = heatmap_data.loc[
        heatmap_data.sum(axis=1).sort_values(ascending=True).index
    ]

    im = axes[1].imshow(
        heatmap_data.values, cmap='YlOrRd', aspect='auto',
        vmin=0, vmax=heatmap_data.values.max(),
    )

    axes[1].set_xticks(range(len(heatmap_data.columns)))
    axes[1].set_xticklabels(heatmap_data.columns, rotation=45, ha='right')
    axes[1].set_yticks(range(len(heatmap_data.index)))
    axes[1].set_yticklabels(heatmap_data.index)
    axes[1].set_title('Director × Genre heatmap (appearances)')

    # Add text annotations inside cells
    for i in range(len(heatmap_data.index)):
        for j in range(len(heatmap_data.columns)):
            val = heatmap_data.values[i, j]
            if val > 0:
                axes[1].text(
                    j, i, str(int(val)),
                    ha='center', va='center', fontweight='bold',
                    fontsize=11,
                    color='white' if val >= 3 else 'black',
                )

    plt.colorbar(im, ax=axes[1], label='Appearances', shrink=0.8)

    plt.tight_layout()
    path = os.path.join(output_dir, "Q3_directors.png")
    plt.savefig(path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  Saved: {path}")

    # --- Answer ---
    top = director_counts.index[0]
    top_count = director_counts.values[0]
    versatile = genres_per_director[genres_per_director >= 3].sort_values(
        ascending=False)

    print(f"\n  ANSWER:")
    print(f"  -> Most frequent director: {top} ({top_count} appearances)")
    print(f"  -> Most versatile (3+ genres):")
    for d, n in versatile.items():
        genres = df[df['director'] == d]['genre'].unique()
        print(f"      {d}: {n} genres ({', '.join(genres)})")
    specialist = genres_per_director[genres_per_director == 1]
    specialist_top = df[df['director'].isin(specialist.index)][
        'director'].value_counts().head(3)
    print(f"  -> Top specialists (1 genre only):")
    for d, c in specialist_top.items():
        g = df[df['director'] == d]['genre'].iloc[0]
        print(f"      {d}: {c} appearances, all in {g}")


# =============================================================================
# MAIN
# =============================================================================

def main():
    """
    Main pipeline:
      1. Load CSV data (pd.concat)
      2. Clean and wrangle (fillna, dropna, map, duplicated)
      3. Transform (pd.cut, groupby+agg, pd.crosstab)
      4. Visualize and answer questions
    """
    print("\n" + "=" * 70)
    print("  FILMAFFINITY DATA ANALYSIS")
    print("  Programming for Data Science - Final Project")
    print("=" * 70)

    # Step 1: Load
    df = load_data(DATA_DIR)

    # Step 2: Clean
    df = clean_data(df)

    # Step 3: Transform
    df, genre_stats, decade_stats, director_genre_ct = transform_data(df)

    # Step 4: Visualize and answer
    question_1(df, genre_stats, OUTPUT_DIR)
    question_2(df, decade_stats, OUTPUT_DIR)
    question_3(df, director_genre_ct, OUTPUT_DIR)

    # --- Final summary ---
    print("\n" + "=" * 70)
    print("  ANALYSIS COMPLETE")
    print("=" * 70)
    print(f"  Movies analyzed: {len(df)}")
    print(f"  Genres: {df['genre'].nunique()} "
          f"({', '.join(df['genre'].unique())})")
    print(f"  Years: {df['year'].min()} – {df['year'].max()}")
    print(f"  Directors: {df['director'].nunique()}")
    print(f"  Countries: {df['country'].nunique()}")
    print(f"\n  Plots saved to: {OUTPUT_DIR}/")
    for f in sorted(os.listdir(OUTPUT_DIR)):
        if f.endswith('.png'):
            print(f"    - {f}")


if __name__ == "__main__":
    main()
