"""
=============================================================================
PART 2: Data Manipulation and Visualization
=============================================================================
Programming for Data Science - Final Project
Universidad Politécnica de Madrid

Description:
    Loads the CSV files generated by the scraper (Part 1), performs
    data manipulation/wrangling/transformation using techniques covered
    in the course, and answers 3 analysis questions with visualizations.

    Questions:
      Q1: Which genre has the highest average rating, and how do
          rating distributions compare across genres?
      Q2: Is there a "golden era" of cinema? How are top-rated films
          distributed across decades?
      Q3: Which directors dominate top-rated lists? Are they genre
          specialists or versatile across genres?

    Course techniques used:
      - pd.concat           (04_data_wrangling: Concatenating Data Sets)
      - fillna, dropna      (05_data_transformation: Handling Missing Data)
      - astype, to_numeric  (03_data_manipulation: Data Types)
      - map                 (05_data_transformation: Function or Mapping)
      - duplicated          (05_data_transformation: Removing Duplicates)
      - pd.cut              (05_data_transformation: Discretization/Binning)
      - groupby + agg       (04_data_wrangling: Group-by Object)
      - pd.crosstab         (04_data_wrangling: Cross-tabulation)
      - value_counts         (06_use_case: Data Arrangement)
      - sort_values          (03_data_manipulation: Sorting and Ranking)

Dependencies:
    pip install pandas plotly kaleido numpy

Usage:
    python analysis.py
=============================================================================
"""

import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import os
import glob


# =============================================================================
# CONFIGURATION
# =============================================================================

DATA_DIR = "data"
OUTPUT_DIR = "plots"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Genre colors (consistent across all plots)
GENRE_COLORS = {
    'Drama':    '#3266ad',
    'Comedy':   '#639922',
    'Thriller': '#BA7517',
    'Sci-Fi':   '#00cccc',
    'Horror':   '#A32D2D',
}


# =============================================================================
# STEP 1: DATA LOADING — pd.concat (04_data_wrangling)
# =============================================================================

def load_data(data_dir):
    """
    Load all CSV files from Part 1 and combine into a single DataFrame.

    Uses pd.concat to concatenate multiple DataFrames, as covered in
    04_data_wrangling (Concatenating Data Sets).

    Parameters:
        data_dir (str): Path to directory with CSV files.

    Returns:
        pd.DataFrame: Combined DataFrame with all genres.
    """
    print("=" * 70)
    print("STEP 1: DATA LOADING (pd.concat)")
    print("=" * 70)

    csv_files = sorted(glob.glob(os.path.join(data_dir, "filmaffinity_*.csv")))

    if not csv_files:
        raise FileNotFoundError(f"No CSV files found in {data_dir}")

    # Read each CSV into a list of DataFrames
    dataframes = []
    for filepath in csv_files:
        df = pd.read_csv(filepath, encoding='utf-8-sig')
        genre = os.path.basename(filepath).replace(
            "filmaffinity_", "").replace(".csv", "")
        print(f"  Loaded: {os.path.basename(filepath)} "
              f"-> {len(df)} rows, genre='{genre}'")
        dataframes.append(df)

    # Concatenate all DataFrames (pd.concat from 04_data_wrangling)
    df = pd.concat(dataframes, ignore_index=True)

    print(f"\n  Combined: {df.shape[0]} rows x {df.shape[1]} columns")
    print(f"  Columns: {list(df.columns)}")

    return df


# =============================================================================
# STEP 2: DATA WRANGLING & CLEANING
#   - isnull, fillna, dropna  (05_data_transformation: Missing Data)
#   - astype, to_numeric       (03_data_manipulation)
#   - map                      (05_data_transformation: Mapping)
#   - duplicated               (05_data_transformation: Removing Duplicates)
# =============================================================================

def clean_data(df):
    """
    Clean and wrangle the raw DataFrame.

    Techniques used (all from course slides):
      - isnull().sum()   -> detect missing values
      - fillna()         -> fill missing text fields
      - dropna()         -> drop rows without essential fields
      - astype()         -> convert data types
      - map()            -> standardize genre labels
      - duplicated()     -> detect movies appearing in multiple genres

    Parameters:
        df (pd.DataFrame): Raw combined DataFrame.

    Returns:
        pd.DataFrame: Cleaned DataFrame.
    """
    print("\n" + "=" * 70)
    print("STEP 2: DATA WRANGLING & CLEANING")
    print("=" * 70)

    # --- 2.1: Check for missing values (isnull from 05_data_transformation) ---
    print("\n  2.1 Missing values:")
    missing = df.isnull().sum()
    print(missing[missing > 0].to_string()
          if missing.sum() > 0 else "    None found")

    # --- 2.2: Handle missing values (fillna from 05_data_transformation) ---
    # Fill missing text fields with 'Unknown'
    for col in ['director', 'cast', 'country']:
        n_missing = df[col].isnull().sum()
        if n_missing > 0:
            df[col] = df[col].fillna('Unknown')
            print(f"  -> Filled {n_missing} missing '{col}' with 'Unknown'")

    # Drop rows without year (essential for decade analysis)
    rows_before = len(df)
    df = df.dropna(subset=['year'])
    dropped = rows_before - len(df)
    if dropped > 0:
        print(f"  -> Dropped {dropped} rows with missing year")

    # --- 2.3: Type conversion (astype from 03_data_manipulation) ---
    df['year'] = df['year'].astype(int)
    df['rating'] = pd.to_numeric(df['rating'], errors='coerce')
    df['votes'] = pd.to_numeric(df['votes'], errors='coerce').fillna(0).astype(int)
    print("  2.3 Type conversions: year->int, rating->float, votes->int")

    # --- 2.4: Standardize genre labels (map from 05_data_transformation) ---
    genre_labels = {
        'drama': 'Drama',
        'comedy': 'Comedy',
        'thriller': 'Thriller',
        'sci_fi': 'Sci-Fi',
        'horror': 'Horror',
    }
    df['genre'] = df['genre'].map(genre_labels)
    print(f"  2.4 Genre labels standardized: {list(df['genre'].unique())}")

    # --- 2.5: Detect duplicates (duplicated from 05_data_transformation) ---
    dupes = df[df.duplicated(subset=['title', 'year'], keep=False)]
    n_dupes = dupes['title'].nunique()
    print(f"\n  2.5 Duplicate detection: {n_dupes} movies appear in 2+ genres")
    if n_dupes > 0:
        for title in dupes['title'].unique()[:5]:
            genres = dupes[dupes['title'] == title]['genre'].tolist()
            print(f"      '{title}' -> {genres}")
        if n_dupes > 5:
            print(f"      ... and {n_dupes - 5} more")

    # --- Summary ---
    print(f"\n  Final: {df.shape[0]} rows x {df.shape[1]} columns")
    print(f"  Year range: {df['year'].min()} – {df['year'].max()}")
    print(f"  Rating range: {df['rating'].min():.1f} – {df['rating'].max():.1f}")

    return df


# =============================================================================
# STEP 3: DATA TRANSFORMATION
#   - Derived column: decade     (arithmetic on year)
#   - pd.cut                     (05_data_transformation: Discretization)
#   - groupby + agg              (04_data_wrangling: Group-by Object)
#   - pd.crosstab                (04_data_wrangling)
#   - value_counts               (06_use_case: Data Arrangement)
# =============================================================================

def transform_data(df):
    """
    Create derived columns and aggregated views for analysis.

    Techniques used:
      - Derived column: decade = (year // 10) * 10
      - pd.cut: bin ratings into categories
      - groupby + agg: compute stats per genre and decade
      - pd.crosstab: director × genre matrix
      - value_counts: director frequency

    Parameters:
        df (pd.DataFrame): Cleaned DataFrame.

    Returns:
        tuple: (df, genre_stats, decade_stats, director_genre_ct)
    """
    print("\n" + "=" * 70)
    print("STEP 3: DATA TRANSFORMATION")
    print("=" * 70)

    # --- 3.1: Create decade column (derived from year) ---
    df['decade'] = (df['year'] // 10) * 10
    df['decade_label'] = df['decade'].astype(str) + 's'
    print(f"  3.1 Created 'decade' column: "
          f"{sorted(df['decade'].unique())}")

    # --- 3.2: Discretization with pd.cut (05_data_transformation) ---
    # Bin ratings into categories using pd.cut
    bins = [0, 7.5, 8.0, 8.5, 10]
    labels = ['Good (≤7.5)', 'Very Good (7.6–8.0)',
              'Excellent (8.1–8.5)', 'Outstanding (>8.5)']
    df['rating_category'] = pd.cut(df['rating'], bins=bins, labels=labels)
    print(f"  3.2 Rating categories (pd.cut):")
    # value_counts (06_use_case)
    cat_counts = df['rating_category'].value_counts()
    for cat, count in cat_counts.items():
        print(f"      {cat}: {count} movies")

    # --- 3.3: Genre statistics (groupby + agg from 04_data_wrangling) ---
    genre_stats = df.groupby('genre').agg(
        mean_rating=('rating', 'mean'),
        median_rating=('rating', 'median'),
        std_rating=('rating', 'std'),
        min_rating=('rating', 'min'),
        max_rating=('rating', 'max'),
        total_votes=('votes', 'sum'),
        avg_votes=('votes', 'mean'),
        movie_count=('title', 'count'),
    ).round(2)
    # sort_values (03_data_manipulation)
    genre_stats = genre_stats.sort_values('mean_rating', ascending=False)
    print(f"\n  3.3 Genre statistics (groupby + agg):")
    print(genre_stats.to_string())

    # --- 3.4: Decade statistics (groupby + agg) ---
    decade_stats = df.groupby(['decade', 'decade_label']).agg(
        mean_rating=('rating', 'mean'),
        movie_count=('title', 'count'),
        avg_votes=('votes', 'mean'),
    ).round(2).reset_index()
    decade_stats = decade_stats.sort_values('decade')
    print(f"\n  3.4 Decade statistics:")
    print(decade_stats.to_string(index=False))

    # --- 3.5: Director × Genre cross-tabulation (pd.crosstab) ---
    # pd.crosstab from 04_data_wrangling
    director_genre_ct = pd.crosstab(df['director'], df['genre'])

    # Filter to directors with 2+ total appearances
    director_totals = director_genre_ct.sum(axis=1)
    director_genre_ct = director_genre_ct[director_totals >= 2]
    director_genre_ct = director_genre_ct.loc[
        director_genre_ct.sum(axis=1).sort_values(ascending=False).index
    ]
    print(f"\n  3.5 Director × Genre crosstab "
          f"({len(director_genre_ct)} directors with 2+ appearances):")
    print(director_genre_ct.head(10).to_string())

    return df, genre_stats, decade_stats, director_genre_ct


# =============================================================================
# STEP 4: VISUALIZATION & DASHBOARD GENERATION
# =============================================================================

def create_q1_figure(df, genre_stats):
    """
    Q1: Which genre has the highest average rating, and how do
    rating distributions compare across genres?
    
    Plots:
      Box plot + Bar chart with error bars
    """
    print("\n  Generating Q1 Plotly figure...")
    genres_order = genre_stats.index.tolist()
    
    fig = make_subplots(rows=1, cols=2, subplot_titles=(
        'Rating distributions by genre',
        'Average rating by genre'
    ))
    
    # --- Plot A: Box plot ---
    for genre in genres_order:
        genre_df = df[df['genre'] == genre]
        fig.add_trace(
            go.Box(
                y=genre_df['rating'],
                name=genre,
                line_color='white',
                fillcolor=GENRE_COLORS[genre],
                opacity=0.8,
                boxpoints=False, # no individual points
                hoverinfo='y',   # show only y-stats (median, q1, q3, etc)
            ),
            row=1, col=1
        )
        
    # --- Plot B: Bar chart with error bars ---
    fig.add_trace(
        go.Bar(
            x=genres_order,
            y=genre_stats['mean_rating'],
            error_y=dict(type='data', array=genre_stats['std_rating'], visible=True),
            marker_color=[GENRE_COLORS[g] for g in genres_order],
            marker_line_color='black',
            marker_line_width=1,
            opacity=0.85,
            text=genre_stats['mean_rating'].apply(lambda x: f"{x:.2f}"),
            textposition='outside',
            hovertemplate="Genre: %{x}<br>Avg Rating: %{y:.2f}<br>Movies: %{customdata[0]}<extra></extra>",
            customdata=genre_stats[['movie_count']].values,
        ),
        row=1, col=2
    )

    fig.update_layout(
        template='plotly_dark',
        hovermode='closest',  # Only show box stats when hovering the box
        showlegend=False,
        yaxis=dict(title='Rating (0-10)', range=[7.3, 9.1]),
        yaxis2=dict(title='Average Rating', range=[7.0, 9.0]),
        height=600
    )
    
    return fig

def create_q2_figure(df, decade_stats):
    """
    Q2: Is there a "golden era" of cinema? How are top-rated films
    distributed across decades, and does average rating vary by era?
    
    Plots:
      Timeline dual-axis + Stacked area
    """
    print("  Generating Q2 Plotly figure...")
    ds = decade_stats.sort_values('decade')
    
    fig = make_subplots(rows=1, cols=2, 
                       subplot_titles=('Movie count and avg rating by decade', 
                                       'Genre distribution over time'),
                       specs=[[{"secondary_y": True}, {"secondary_y": False}]])
    
    # --- Plot A: Dual-axis Timeline ---
    fig.add_trace(
        go.Bar(
            x=ds['decade_label'],
            y=ds['movie_count'],
            name='Number of movies',
            marker_color='#3266ad',
            opacity=0.7,
            hovertemplate="Decade: %{x}<br>Total Movies: %{y}<extra></extra>"
        ),
        row=1, col=1, secondary_y=False
    )
    
    fig.add_trace(
        go.Scatter(
            x=ds['decade_label'],
            y=ds['mean_rating'],
            name='Avg rating',
            mode='lines+markers',
            line=dict(color='#A32D2D', width=3),
            marker=dict(size=8),
            hovertemplate="Decade: %{x}<br>Avg Rating: %{y:.2f}<extra></extra>"
        ),
        row=1, col=1, secondary_y=True
    )
    
    # --- Plot B: Stacked area chart ---
    # Prepare data for stacked area
    pivot = pd.crosstab(df['decade_label'], df['genre'])
    decade_order = sorted(df['decade_label'].unique(), key=lambda x: int(x.replace('s', '')))
    pivot = pivot.reindex(decade_order)
    
    for genre in pivot.columns:
        fig.add_trace(
            go.Scatter(
                x=pivot.index,
                y=pivot[genre],
                name=genre,
                mode='lines',
                stackgroup='one',
                fillcolor=GENRE_COLORS[genre],
                line=dict(width=0.5, color='black'),
                hovertemplate="Decade: %{x}<br>Genre: " + genre + "<br>Movies: %{y}<extra></extra>"
            ),
            row=1, col=2
        )
        
    fig.update_layout(
        template='plotly_dark',
        height=700, # Increased height to accommodate legend
        margin=dict(t=200),  # Much more generous top margin
        legend=dict(orientation="h", yanchor="bottom", y=1.2, xanchor="right", x=1)
    )
    fig.update_yaxes(title_text="Movies count", row=1, col=1, secondary_y=False)
    fig.update_yaxes(title_text="Average rating", range=[7.4, 8.5], row=1, col=1, secondary_y=True)
    fig.update_yaxes(title_text="Movies count", row=1, col=2)
    
    return fig

def create_q3_figure(df, director_genre_ct):
    """
    Q3: Which directors dominate across multiple genre rankings?
    Are they genre specialists or versatile across genres?
    
    Plots:
      Horizontal bar + Heatmap
    """
    print("  Generating Q3 Plotly figure...")
    director_counts = df['director'].value_counts().head(15)
    top_directors = director_counts.index.tolist()
    
    genres_per_director = df.groupby('director')['genre'].nunique()
    
    # Versatility array for hover
    versatility_info = []
    colors = []
    for d in top_directors:
        n = genres_per_director.get(d, 1)
        if n >= 3:
            colors.append('#534AB7')
            versatility_info.append('Versatile (3+ genres)')
        elif n == 2:
            colors.append('#1D9E75')
            versatility_info.append('2 genres')
        else:
            colors.append('#BA7517')
            versatility_info.append('Specialist (1 genre)')
            
    fig = make_subplots(rows=1, cols=2, 
                       subplot_titles=('Top 15 directors by frequency', 
                                       'Director x Genre Heatmap'))
    
    # --- Plot A: Horizontal Bar ---
    avg_ratings = [df[df['director'] == d]['rating'].mean() for d in top_directors]
    
    fig.add_trace(
        go.Bar(
            y=top_directors[::-1], # Reversed for top-down display
            x=director_counts.values[::-1],
            orientation='h',
            marker_color=colors[::-1],
            marker_line_color='black',
            marker_line_width=1,
            text=[f"{n} genres (avg {r:.1f})" for n, r in zip([genres_per_director.get(d,1) for d in top_directors][::-1], avg_ratings[::-1])],
            textposition='inside',
            insidetextanchor='end',
            customdata=versatility_info[::-1],
            hovertemplate="<b>%{y}</b><br>Appearances: %{x}<br>Style: %{customdata}<extra></extra>"
        ),
        row=1, col=1
    )
    
    # --- Plot B: Heatmap ---
    heatmap_data = director_genre_ct.head(15)
    heatmap_data = heatmap_data.loc[heatmap_data.sum(axis=1).sort_values().index]
    
    # Create hover text matrix showing movie titles
    hover_text = []
    for director in heatmap_data.index:
        row_text = []
        for genre in heatmap_data.columns:
            movies = df[(df['director'] == director) & (df['genre'] == genre)]['title'].tolist()
            if movies:
                row_text.append(f"<b>{director} - {genre}</b><br>" + "<br>".join(movies))
            else:
                row_text.append(f"No movies")
        hover_text.append(row_text)
        
    fig.add_trace(
        go.Heatmap(
            z=heatmap_data.values,
            x=heatmap_data.columns,
            y=heatmap_data.index,
            colorscale='YlOrRd',
            showscale=True,
            text=hover_text,
            hovertemplate="%{text}<extra></extra>",
            texttemplate="%{z}",
            textfont={"size": 12}
        ),
        row=1, col=2
    )
    
    fig.update_layout(
        template='plotly_dark',
        height=650,
        showlegend=False
    )
    fig.update_xaxes(title_text="Appearances in top-30 lists", row=1, col=1)
    
    return fig

def create_data_table(df):
    """
    Exploratory Data Table
    An interactive table to search, sort, and filter all movies.
    """
    print("  Generating Data Explorer table...")
    # Select and format columns for display (URL removed as requested)
    display_df = df[['rank', 'title', 'year', 'director', 'genre', 'rating', 'votes']].copy()
    
    fig = go.Figure(data=[go.Table(
        header=dict(
            values=list(display_df.columns),
            fill_color='#2c3e50',
            font=dict(color='white', size=13),
            align='center'
        ),
        cells=dict(
            values=[display_df[k] for k in display_df.columns],
            fill_color='#1a242f',
            font=dict(color='white', size=12),
            align='center',
            height=30
        )
    )])
    
    fig.update_layout(
        title="Exploratory Data Table (Full List)",
        template='plotly_dark',
        height=600,
        margin=dict(l=20, r=20, t=50, b=20)
    )
    
    return fig

def save_static_figs(fig_q1, fig_q2, fig_q3, output_dir):
    """Saves static PNG representations for fallback/reports."""
    print("\n" + "=" * 70)
    print("SAVING STATIC BACKUPS (PNG)")
    print("=" * 70)
    # Re-enabled static image export
    fig_q1.write_image(os.path.join(output_dir, "Q1_genre_ratings.png"), width=1400, height=700, scale=1.5)
    fig_q2.write_image(os.path.join(output_dir, "Q2_golden_era.png"), width=1400, height=700, scale=1.5)
    fig_q3.write_image(os.path.join(output_dir, "Q3_directors.png"), width=1400, height=700, scale=1.5)
    print("  ✓ Q1, Q2, and Q3 plots saved as PNG in 'plots/' folder.")

def create_dashboard(df, genre_stats, decade_stats, director_genre_ct, output_dir):
    """
    Combines all figures into a single HTML dashboard with tabs.
    """
    print("\n" + "=" * 70)
    print("GENERATING INTERACTIVE DASHBOARD")
    print("=" * 70)
    
    fig_q1 = create_q1_figure(df, genre_stats)
    fig_q2 = create_q2_figure(df, decade_stats)
    fig_q3 = create_q3_figure(df, director_genre_ct)
    fig_table = create_data_table(df)
    
    # HTML generation (Prohibited to touch logic)
    
    # To combine multiple Plotly figures into an elegant HTML, 
    # we generate HTML div representations and wrap them with simple JS/CSS for tabs.
    html_q1 = fig_q1.to_html(full_html=False, include_plotlyjs='cdn')
    html_q2 = fig_q2.to_html(full_html=False, include_plotlyjs=False)
    html_q3 = fig_q3.to_html(full_html=False, include_plotlyjs=False)
    html_table = fig_table.to_html(full_html=False, include_plotlyjs=False)
    
    html_template = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Filmaffinity Analysis Dashboard</title>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #111; color: #fff; margin: 0; padding: 20px; }}
            .header {{ text-align: center; margin-bottom: 20px; }}
            .tabs {{ display: flex; justify-content: center; gap: 10px; margin-bottom: 20px; }}
            .tab-btn {{ background-color: #2c3e50; color: white; border: none; padding: 10px 20px; cursor: pointer; border-radius: 5px; font-weight: bold; transition: background-color 0.3s; }}
            .tab-btn:hover {{ background-color: #34495e; }}
            .tab-btn.active {{ background-color: #3498db; }}
            .tab-content {{ display: none; background-color: #1a1a1a; padding: 20px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.5); }}
            .tab-content.active {{ display: block; }}
            .stats-container {{ display: flex; justify-content: space-around; background-color: #1a1a1a; padding: 15px; border-radius: 10px; margin-bottom: 20px; }}
            .stat-box {{ text-align: center; }}
            .stat-value {{ font-size: 24px; font-weight: bold; color: #3498db; }}
            .stat-label {{ font-size: 14px; color: #aaa; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>🎬 Filmaffinity Top Movies Interactive Dashboard</h1>
            <p>Programming for Data Science — Final Project Analysis</p>
        </div>
        
        <div class="stats-container">
            <div class="stat-box">
                <div class="stat-value">{len(df)}</div>
                <div class="stat-label">Total Movies</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{df['genre'].nunique()}</div>
                <div class="stat-label">Genres Analyzed</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{df['director'].nunique()}</div>
                <div class="stat-label">Unique Directors</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{df['year'].min()} - {df['year'].max()}</div>
                <div class="stat-label">Timespan</div>
            </div>
        </div>

        <div class="tabs">
            <button class="tab-btn active" onclick="openTab(event, 'Q1')">Q1: Genre Ratings</button>
            <button class="tab-btn" onclick="openTab(event, 'Q2')">Q2: Golden Era</button>
            <button class="tab-btn" onclick="openTab(event, 'Q3')">Q3: Director Dominance</button>
            <button class="tab-btn" onclick="openTab(event, 'Explorer')">Data Explorer</button>
        </div>

        <div id="Q1" class="tab-content active">
            {html_q1}
        </div>
        <div id="Q2" class="tab-content">
            {html_q2}
        </div>
        <div id="Q3" class="tab-content">
            {html_q3}
        </div>
        <div id="Explorer" class="tab-content">
            {html_table}
        </div>

        <script>
            function openTab(evt, tabName) {{
                var i, tabcontent, tablinks;
                tabcontent = document.getElementsByClassName("tab-content");
                for (i = 0; i < tabcontent.length; i++) {{
                    tabcontent[i].className = tabcontent[i].className.replace(" active", "");
                }}
                tablinks = document.getElementsByClassName("tab-btn");
                for (i = 0; i < tablinks.length; i++) {{
                    tablinks[i].className = tablinks[i].className.replace(" active", "");
                }}
                document.getElementById(tabName).className += " active";
                evt.currentTarget.className += " active";
                
                // Trigger window resize to fix plotly rendering issues in hidden inactive tabs
                window.dispatchEvent(new Event('resize'));
            }}
        </script>
    </body>
    </html>
    """
    
    dash_path = os.path.join(output_dir, "interactive_dashboard.html")
    with open(dash_path, "w", encoding="utf-8") as f:
        f.write(html_template)
        
    print(f"  ✓ Dashboard saved successfully to: {dash_path}")
    return dash_path


# =============================================================================
# MAIN
# =============================================================================

def main():
    """
    Main pipeline:
      1. Load CSV data (pd.concat)
      2. Clean and wrangle (fillna, dropna, map, duplicated)
      3. Transform (pd.cut, groupby+agg, pd.crosstab)
      4. Generate Interactive Dashboard
    """
    print("\n" + "=" * 70)
    print("  FILMAFFINITY DATA ANALYSIS - INTERACTIVE")
    print("  Programming for Data Science - Final Project")
    print("=" * 70)

    # Step 1: Load
    df = load_data(DATA_DIR)

    # Step 2: Clean
    df = clean_data(df)

    # Step 3: Transform
    df, genre_stats, decade_stats, director_genre_ct = transform_data(df)

    # Step 4: Visualize (Interactive Dashboard)
    dash_path = create_dashboard(df, genre_stats, decade_stats, director_genre_ct, OUTPUT_DIR)

    # Step 5: Save Static Backups (PNG) - Moved to end to ensure dashboard is generated first
    fig_q1 = create_q1_figure(df, genre_stats)
    fig_q2 = create_q2_figure(df, decade_stats)
    fig_q3 = create_q3_figure(df, director_genre_ct)
    save_static_figs(fig_q1, fig_q2, fig_q3, OUTPUT_DIR)

    # --- Final summary ---
    print("\n" + "=" * 70)
    print("  ANALYSIS COMPLETE")
    print("=" * 70)
    print(f"\n  Dashboard Location: {dash_path}")
    print("  Double-click the HTML file to open it in your web browser!")


if __name__ == "__main__":
    main()
